£Lerror_reason¢DtypeEvalueYvHTTPSConnectionPool(host='archive.ics.uci.edu', port=443): Max retries exceeded with url: /ml/datasets.html?format=mat&task=&att=cat&area=soc&numAtt=10to100&numIns=greater1000&type=seq&sort=typeUp&view=list (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10f581650>, 'Connection to archive.ics.uci.edu timed out. (connect timeout=2)'))Ihttp_code¢DtypeEvalueÛQdownload_complete¢DtypeEvalueı