£Lerror_reason¢DtypeEvalueY9HTTPConnectionPool(host='tps.ics.uci.edu', port=80): Max retries exceeded with url: /svn/projects/simse/trunk/simse/res/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x119684290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))Ihttp_code¢DtypeEvalueÛQdownload_complete¢DtypeEvalueı