£Lerror_reason¢DtypeEvalueYxHTTPSConnectionPool(host='archive.ics.uci.edu', port=443): Max retries exceeded with url: /ml/datasets.html?format=&task=&att=&area=soc&numAtt=10to100&numIns=less100&type=ts&sort=attTypeDown&view=table (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000184A22B0>, 'Connection to archive.ics.uci.edu timed out. (connect timeout=2)'))Ihttp_code¢DtypeEvalueÛQdownload_complete¢DtypeEvalueı